# This example demonstrates creating and attaching a managed IAM policy to a user
# Managed policies are:
# - Standalone policy objects that can be attached to multiple users, groups, or roles
# - Reusable across multiple entities
# - Maintained separately from the entities they're attached to
# - Version controlled and can be rolled back if needed

# Create an IAM user that will use the managed policy
resource "aws_iam_user" "example" {
  name = "example-user"
}

# Create the policy document using AWS's policy document data source
# This provides a cleaner way to define the policy compared to inline JSON
data "aws_iam_policy_document" "s3_list" {
  statement {
    effect    = "Allow"                         # Allow these actions (as opposed to Deny)
    actions   = ["s3:ListBucket"]               # Permission to list contents of an S3 bucket
    resources = ["arn:aws:s3:::example-bucket"] # ARN of the specific bucket this applies to
  }
}

# Create the managed policy resource
# This policy exists independently and can be attached to multiple IAM entities
resource "aws_iam_policy" "s3_list" {
  name   = "managed-s3-list"                         # Name of the managed policy
  policy = data.aws_iam_policy_document.s3_list.json # Use the JSON generated by the policy document
}

# Create the attachment between the user and the managed policy
# This is a separate resource that creates the relationship between user and policy
resource "aws_iam_user_policy_attachment" "attach" {
  user       = aws_iam_user.example.name  # Reference to the IAM user
  policy_arn = aws_iam_policy.s3_list.arn # ARN of the managed policy to attach
}
